import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/styles/globals.css';  // Adjusted import to reflect new location of globals.css
import Navbar from '@/components/layout/Navbar';
import { CartProvider } from '@/hooks/useCart';
import Footer from '@/components/layout/Footer'; // Importing Footer component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ROLYO CLOTHING",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <CartProvider>
          <Navbar />
          {children}
          <Footer /> {/* Footer component added back to the layout */}
        </CartProvider>
      </body>
    </html>
  );
}
